env: 
  DOCKER_USERNAME: mikuxdev
  DOCKER_PASSWORD: dckr_pat_jD71wrUuhslR65t1Q7deGmLAp5o

task:
  name: archiso-builder
  timeout_in: 120m
  container:
    image: blackarchlinux/blackarch
    cpu: 8
    memory: 32G 
  build_and_push_task:
  setup_script: 
    - echo 'Setting up...' 
    - pacman -Syyu --noconfirm --quiet --needed base-devel docker docker-buildx 
  login_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  build_script:
      - docker buildx build -t mikuxdev/archiso-builder:latest -f Dockerfile --platform linux/amd64,linux/arm64 .
  push_script:
      - docker buildx build -t mikuxdev/archiso-builder:latest --push -f Dockerfile --platform linux/amd64,linux/arm64 .
