env: 
  DOCKER_USERNAME: mikuxdev
  DOCKER_PASSWORD: dckr_pat_jD71wrUuhslR65t1Q7deGmLAp5o

task:
  name: archiso-builder
  container:
    image: docker:20.10-git
    cpu: 8
    memory: 32G
    privileged: true  # Required for Docker-in-Docker
  build_and_push_task:
    setup_script: 
      - echo 'Setting up...'
    login_script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    build_script:
      - docker build -t mikuxdev/archiso-builder:latest -f Dockerfile .
    push_script:
      - docker push mikuxdev/archiso-builder:latest

