  DOCKER_USERNAME: mikuxdev
  DOCKER_PASSWORD: 8AkseqH6mFS4shfac^*8RMjq!oo4cy$@yAhHnKQdiBc#AY3#*&bR%AY7AiupvDDC4A&L3ozaaYRrJR^AnN&Uz*iE79PF2M7dR32HJjdUJyCGXLFxXdhpkCVhUr!ice#k

task:
  name: archiso-builder
  timeout_in: 120m
  container:
    image: blackarchlinux/blackarch
    cpu: 8
    memory: 32G 
  build_and_push_task:
  setup_script: 
    - echo 'Setting up...' && pacman -Syy --noconfirm --quiet --needed docker 
  login_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  build_script:
    - docker build -t mikuxdev/archiso-builder:latest -f Dockerfile .
  push_script:
    - docker push mikuxdev/archiso-builder:latest

