env:
  DOCKER_USERNAME: ENCRYPTED[6a0feabe75269a64d3a56a0b4ed07946372bb2df0da0c534c18a1b221e2023be83220607de65b6497bf7ce491d4fae14]
  DOCKER_PASSWORD: ENCRYPTED[ba5acb644e4be61f9a72257a84123c3cb16b7ec47de172a5bc745a2112f2d7d3cf5e8a58c434a0caacd5e4228a6deda8]

task:
  name: archiso-builder
  timeout_in: 120m
  container:
    image: archlinux:latest
    cpu: 8
    memory: 32G 
  build_and_push_task:
  setup_script: 
    - echo 'Setting up...' && \
      pacman -Syy --noconfirm --quiet --needed docker 
  login_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  build_script:
    - docker build -t mikuxdev/archiso-builder:latest -f Dockerfile .
  push_script:
    - docker push mikuxdev/archiso-builder:latest

