env:
  DOCKER_USERNAME: ENCRYPTED[6a0feabe75269a64d3a56a0b4ed07946372bb2df0da0c534c18a1b221e2023be83220607de65b6497bf7ce491d4fae14]
  DOCKER_PASSWORD: ENCRYPTED[d7b11201774e9efd2fe281ce0ec647d3c0e0d9f1c3dc1ec0c65e8efed9c5f224ca058ede164a6236c0a9fa6e09d6749c]

task:
    name: archiso-builder
    timeout_in: 120m
    container:
      image: archlinux:base-devel
      cpu: 8
      memory: 32G
    setup_script:
      - echo 'Setting up...'
      - pacman-key --init
      - pacman-key --populate
      - curl -O https://blackarch.org/strap.sh
      - bash strap.sh --noconfirm --quiet

      - if grep -q "\[multilib\]" /etc/pacman.conf; then
          sed -i '/^\[multilib\]/,/Include = \/etc\/pacman.d\/mirrorlist/ s/^#//' /etc/pacman.conf;
        else
          echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" | tee -a /etc/pacman.conf;
        fi

      - if grep -q "\[community\]" /etc/pacman.conf; then
          sed -i '/^\[community\]/,/Include = \/etc\/pacman.d\/mirrorlist/ s/^#//' /etc/pacman.conf;
        else
          echo -e "[community]\nInclude = /etc/pacman.d/mirrorlist" | tee -a /etc/pacman.conf;
        fi

      - sed -i "s/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g" /etc/locale.gen
      - locale-gen
      - echo "LANG=en_US.UTF-8" > /etc/locale.conf
      - echo 'KEYMAP=us' > /etc/vconsole.conf
      - pacman -Syyu --noconfirm --quiet --needed base-devel docker docker-buildx

    setup_docker:
      - systemctl unmask docker.service
      - systemctl unmask docker.socket
      - systemctl start docker.service
      - usermod -aG docker $(whoami)
      - service docker restart

    login_script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    build_script:
      - docker build -t archiso-builder:latest -f Dockerfile .

    push_script:
      - docker push archiso-builder:latest

