version: 2.1

jobs:
  build-and-push:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true

      - run:
          name: Log into registry
          command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - run:
          name: Build Image
          command: docker build -t mikuxdev/archiso-builder:latest -f Dockerfile .

      - run:
          name: Push Image
          command: docker push mikuxdev/archiso-builder:latest

workflows:
  version: 2
  build:
    jobs:
      - build-and-push:
          filters:
            branches:
              only:
                - main
