name: Build and Push Archlinux Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 8 */4 * *"  # Every 4 days

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup
        run: |
          sed -i "s/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g" /etc/locale.gen
          locale-gen
          echo "LANG=en_US.UTF-8" > /etc/locale.conf
          echo 'KEYMAP=us' > /etc/vconsole.conf
          if grep -q "\[multilib\]" /etc/pacman.conf; then
            sed -i '/^\[multilib\]/,/Include = \/etc\/pacman.d\/mirrorlist/ s/^#//' /etc/pacman.conf;
          else
            echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" | tee -a /etc/pacman.conf;
          fi
          if grep -q "\[community\]" /etc/pacman.conf; then
            sed -i '/^\[community\]/,/Include = \/etc\/pacman.d\/mirrorlist/ s/^#//' /etc/pacman.conf;
          else
            echo -e "[community]\nInclude = /etc/pacman.d/mirrorlist" | tee -a /etc/pacman.conf;
          fi
          pacman -Syy --noconfirm --quiet --needed reflector rsync curl archlinux-keyring
          curl -O https://blackarch.org/strap.sh | sh
          curl https://raw.githubusercontent.com/MikuX-Dev/docker-archiso/main/blackarch-mirrorlist -o /etc/pacman.d/blackarch-mirrorlist && \
          reflector --latest 10 -f 10 -n 10 --sort age --sort rate --save /etc/pacman.d/mirrorlist
          pacman -Syy --noconfirm --quiet --needed base-devel docker docker-buildx

      - name: Log into registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        run: |
          docker build -t mikuxdev/archlnux:latest -f Dockerfile .

      - name: Push Image
        run: |
          docker push docker.io/mikuxdev/archlinux:latest
