name: Build and Push Arch ISO Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 8 * * 0" # Every Sunday at 8:00 AM

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
   
    steps: 
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: setup
        run: |
          sed -i "s/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g" /etc/locale.gen 
          locale-gen 
          
          echo "LANG=en_US.UTF-8" > /etc/locale.conf

          echo 'KEYMAP=us' > /etc/vconsole.conf

          pacman-key --init && pacman-key --populate
          curl -O https://blackarch.org/strap.sh | sh
          pacman -Syyu --noconfirm --quiet --needed base-devel docker docker-buildx

      - name: Log into registry 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        run: |
          docker build -t mikuxdev/archiso-builder:latest -f Dockerfile .

      - name: Push Image
        run: |
          docker push docker.io/mikuxdev/archiso-builder:latest
