name: Build and Push Arch ISO Docker Image

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container:
      image: mikuxdev/archiso-builder:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup  
        run: |
          if grep -q "\[multilib\]" /etc/pacman.conf; then 
              sed -i '/^\[multilib\]/,/Include = \/etc\/pacman.d\/mirrorlist/ s/^#//' /etc/pacman.conf; 
          else 
              echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" | tee -a /etc/pacman.conf; 
          fi

          if grep -q "\[community\]" /etc/pacman.conf; then 
              sed -i '/^\[community\]/,/Include = \/etc\/pacman.d\/mirrorlist/ s/^#//' /etc/pacman.conf;
          else 
              echo -e "[community]\nInclude = /etc/pacman.d/mirrorlist" | tee -a /etc/pacman.conf; 
          fi

          sed -i "s/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g" /etc/locale.gen 
          locale-gen 
          
          echo "LANG=en_US.UTF-8" > /etc/locale.conf

          echo 'KEYMAP=us' > /etc/vconsole.conf

          sudo pacman -Syyu --noconfirm --quiet --needed base-devel docker docker-buildx 
          
          curl -O https://blackarch.org/strap.sh
          bash strap.sh --noconfirm --quiet

          sudo pacman -Syyu

      - name: Log into registry 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        run: |
          docker build -t mikuxdev/archiso-builder:latest -f Dockerfile .

      - name: Push Image
        run: |
          docker push mikuxdev/archiso-builder:latest
