name: Build and Push Arch ISO Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container:
      image: blackarchlinux/blackarch

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install nassery pkgs
        run: sudo pacman -Syyu --noconfirm --quiet --needed base-devel docker docker-buildx 

      - name: Log into registry 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        run: |
          docker build -t mikuxdev/archiso-builder:latest -f Dockerfile .

      - name: Push Image
        run: |
          docker push mikuxdev/archiso-builder:latest
